---

- name: Ubuntu Desktop Environment
  hosts: localhost
  vars:
    user: loete
  roles:
    # Common roles:
    - { role: common, become: true }
    - { role: zsh, become: true }
    - { role: adapta-theme, become: true }
    - { role: papirus-icon-theme, become: true }
    - { role: env-settings, become: true }
    - { role: vs-code, become: true }
    - { role: snaps, become: true }
