---

- name: set gpg key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: add docker-ce apt_repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    state: present
    update_cache: yes

- name: install docker ce
  apt:
    name: "{{item}}"
    update_cache: yes
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io