---

- name: Install zsh
  apt: pkg=zsh state=latest update_cache=yes cache_valid_time={{ aptcachetime }}

- name: Change shell to ZSH
  user:
    name: "{{ user }}"
    shell: /usr/bin/zsh
  become: yes

- name: Fetch oh-my-zsh
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/install-oh-my-zsh.sh
    mode: 0755

- name: Install oh-my-zsh
  command: sh /tmp/install-oh-my-zsh.sh

- name: Clone zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "/home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    update: no

- name: Clone zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "/home/{{ user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    update: no

- name: Clone powerlevel9k
  git:
    repo: https://github.com/bhilburn/powerlevel9k.git
    dest: "/home/{{ user }}/.oh-my-zsh/themes/powerlevel9k"
    update: no

- name: copy .zshrc to $HOME
  template:
    src: zshrc.j2
    dest: "/home/{{ user }}/.zshrc"
    owner: "{{ user }}"
    group: "{{ user }}"
