---

oh_my_zsh_custom_plugins:
  - name: zsh-syntax-highlighting
    repo: "git://github.com/zsh-users/zsh-syntax-highlighting.git"
  - name: zsh-autosuggestions
    repo: "git://github.com/zsh-users/zsh-autosuggestions.git"

oh_my_zsh_plugins:
  - git
  - git-flow
  - docker
  - zsh-syntax-highlighting
  - zsh-autosuggestions
