---

- name: configure the adapta-theme APT repositories
  apt_repository:
    repo: "ppa:tista/adapta"
    state: present
    update_cache: yes

- name: install adapta
  apt:
    name: adapta-gtk-theme
    state: latest
    update_cache: true
