---

- name: configure the adapta-theme APT repositories
  apt_repository:
    repo: "ppa:tista/adapta"
    state: present
    update_cache: yes
  become: yes

- name: install adapta-theme
  apt: pkg=adapta-gtk-theme state=latest
  become: yes
