---

- name: Configure the papirus-icon-theme APT repositories
  apt_repository:
    repo: "ppa:papirus/papirus"
    state: present

- name: Install papirus-icon-theme
  apt: pkg=papirus-icon-theme state=latest
  register: papirus_icon_theme
