---

- name: Clone nerd-fonts repo
  git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    dest: "/home/{{ user }}/.local/nerd-fonts"

- name: Install nerd-fonts
  command: "./home/{{ user }}/.local/nerd-fonts/install.sh Noto"
