---

- name: install packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - texlive
    - xzdec
  tags:
    - latex

- name: get apt package facts
  package_facts:
    manager: "auto"
  tags:
    - latex

- name: install vscode extensions if vscode is installed
  become_user: "{{user}}"
  command: "code --install-extension {{item}}"
  with_items:
    - James-Yu.latex-workshop
    - streetsidesoftware.code-spell-checker
    - streetsidesoftware.code-spell-checker-german
  when: '"code" in ansible_facts.packages'
  tags:
    - latex

- name: tlmgr init-usertree
  command: tlmgr init-usertree
  tags:
    - latex

# https://tex.stackexchange.com/questions/429714/tlmgr-remote-repository-is-newer-than-local-2017-2018
- name: fix year issue
  command: tlmgr option repository ftp://tug.org/historic/systems/texlive/2017/tlnet-final
  tags: 
    - latex

- name: install luainputenc.sty
  command: tlmgr install luainputenc
  tags:
    - latex